### гууд
GET http://localhost:8080/info?rac=NC_000001.11&lap=925951&rap=925953&refkey=A

### нет такого
GET http://localhost:8080/info?rac=NC_000001.11&lap=1&rap=1&refkey=Z

### параметра refkey нет
GET http://localhost:8080/info?rac=NC_000001.11&lap=925951&rap=925953

### некорректные параметры
GET http://localhost:8080/info?rac=&lap=-1&rap=xxx&refkey=null

### все аннотации
GET

### ошибка чтения файла (файл переименовать надо)
GET http://localhost:8080/info/debug/all

